---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: no
configure_osx: yes

dotfiles_repo: https://github.com/jakubigla/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .p10k.zsh
  - .zshrc
  - .osx

homebrew_installed_packages:
  - archey
  - awscli
  - azure-cli
  - bash-completion
  - bat
  - ctop
  - direnv
  - dive
  - eksctl
  - fluxctl
  - geoip
  - go
  - helm
  - istioctl
  - jq
  - k9s
  - kind
  - kubebuilder
  - kubectx
  - kubernetes-cli
  - kustomize
  - macvim
  - maven
  - minikube
  - nmap
  - nvm
  - openssl
  - packer
  - pipenv
  - pyenv
  - rsync
  - ruby
  - tfenv
  - tflint
  - tmux
  - tree
  - speedtest-cli
  - youtube-dl
  - yq
  - watch
  - wget
  - wifi-password
  - vault
  - zsh
  - zsh-syntax-highlighting
  - chamber

homebrew_taps:
  - homebrew/core

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - atom
  - anaconda
  - docker
  - firefox
  - google-chrome
  - iterm2
  - keybase
  - microsoft-teams
  - miro
  - intellij-idea-ce
  - kdiff3
  - opera
  - postman
  - qnapi
  - skype
  - slack
  - spectacle
  - spotify
  - transmission
  - tunnelbear
  - vlc
  - wkhtmltopdf
  - aws-vault
  - zoomus

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
